version: '2'
services:
  web:
   image: golang:1.6-onbuild
   ports:
    - 8082:80
   network_mode: bridge
   restart: always
   entrypoint: /entrypoint.sh
   volumes:
    - ./entrypoint.sh:/entrypoint.sh
    - ./code:/go/src/app
    - ./logfile.txt:/logfile #make sure this file exists or docker-compose will make a directory
